### ISSUE TITLE
Update to ASP.Net Core 3.1 - Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder 

### ISSUE THREAD

**Issue by ralfbalzer** [mrahhal/MR.AspNetCore.Jobs#18]
Hi Mohammad, 
I am trying to upgrade my site to Core 3.1 and am getting the following error:

System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'.
   at MR.AspNetCore.Jobs.Models.JobsDbContext.<>c.<OnModelCreating>b__3_0(EntityTypeBuilder`1 b)
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at MR.AspNetCore.Jobs.Models.JobsDbContext.OnModelCreating(ModelBuilder builder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_3(IServiceProvider p)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Add[TEntity](TEntity entity)
   at MR.AspNetCore.Jobs.EFCoreStorageConnection`2.StoreJobAsync(Job job)
   at MR.AspNetCore.Jobs.JobsManager.EnqueueCore(Nullable`1 due, MethodInvocation method)
   at MR.AspNetCore.Jobs.JobsManager.EnqueueAsync[T](Expression`1 methodCall)

Are you planning to udpate the package to support 3.1? 

I thin the issue might be ralted to this issue:
https://github.com/dotnet/aspnetcore/issues/8467

Thanks 
Ralf

**Comment by mrahhal** [comment]
Hi,

Haven't worked on this for a while so I'm pretty sure it'll need an upgrade to support 3.1 yeah. Not exactly sure when I can do that but will try to do it soon.

**Comment by mrahhal** [comment]
Version `0.11.1` supports dotnet 3.1. Please let me know if you face problems after installing it.

**Comment by ralfbalzer** [comment]
That was quick :-)

It got a step further but now I am seeing:

2020-01-15 20:52:52.534 +01:00 [INF] Executed DbCommand (5ms) [Parameters=[@p0='?' (DbType = DateTime2), @p1='?' (Size = 4000), @p2='?' (DbType = DateTime2), @p3='?' (DbType = DateTime2), @p4='?' (DbType = Int32), @p5='?' (Size = 450), @p6='?' (DbType = DateTime2)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Jobs].[Jobs] ([Added], [Data], [Due], [ExpiresAt], [Retries], [StateName], [Updated])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
SELECT [Id]
FROM [Jobs].[Jobs]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();

2020-01-15 20:52:52.783 +01:00 [ERR] An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MR.AspNetCore.Jobs.Server.ProcessingServer.AllProcessorsWaiting()
   at MR.AspNetCore.Jobs.Server.ProcessingServer.Pulse()
   at MR.AspNetCore.Jobs.JobsManager.EnqueueCore(Nullable`1 due, MethodInvocation method)
   at MR.AspNetCore.Jobs.JobsManager.EnqueueAsync[T](Expression`1 methodCall)

I am using an SQL server Datbase.

**Comment by mrahhal** [comment]
Hmm I can't reproduce this one. Does this happen 100% of the time when you enqueue something?

**Comment by ralfbalzer** [comment]
If I submit a job using  await `using _jobsManager.EnqueueAsync<>`, the job is written into the Jobs table but it is never run or completetd.
After deleteing the Jobs.xxx tabels in my database and restarting the app, the tables don't get re-created. So I think there is an issue with creation of the DBContext. 
I have trie some other things, but nothing seems to work.

**Comment by mrahhal** [comment]
I'm not sure I'm following, this seems like a whole other problem than the one you were describing.

**Comment by ralfbalzer** [comment]
I am not sure as the system doesn't log much detail. 

However, when I try to run  `await _jobsManager.EnqueueAsync<ZahlungsProcess>(zahlung => zahlung.ExecuteAsync());` I can see that in my 3.1 version, `_jobsManager _server _context` and `_jobsManager _server _processors` are both Null. In my 2.2 they are not. 
See below the difference:

2.2
![2 2 Anmerkung 2020-01-16 172037](https://user-images.githubusercontent.com/22136154/72543295-d09d5880-3885-11ea-8d7e-4d7aba0e9766.jpg)

3.1
![Anmerkung 2020-01-16 172037](https://user-images.githubusercontent.com/22136154/72543312-d72bd000-3885-11ea-90b9-289629206f9a.jpg)

**Comment by mrahhal** [comment]
And you changed nothing between the 2? Can you check if the call to `host.StartJobsAsync()` is running before your enqueuing?

**Comment by ralfbalzer** [comment]
Sorry - I just realized what it is. As of 3.0 **HostBuilder replaces WebHostBuilder** [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio).
I had changed this in the program.cs file but HostBuilder has obviously not got the StartJobsAsync() Task. It auto corrected it to StartAsync().
Can you add the Task to HostBuilder? 
Would be much appreciated.

**Comment by mrahhal** [comment]
Oh, yes this is something I missed. Here's the new package: `0.11.2` (being validated right now in nuget, should be installable in few minutes). Thanks!

**Comment by ralfbalzer** [comment]
Thanks very much. It's all working again now. 
I really appreciate your quick response.
